# the PostgreSQL database spun up by the docker-compose requires a first time 
# initialization of a USERS and USER_ROLES table required for basic authorization.

#!/bin/bash

set -e
# this is the default entry point generated by the Dockerfile:
/usr/local/bin/docker-entrypoint.sh postgres &
# this modifies the user roles table:
until pg_isready -h database -U sensorthings -d sensorthings; do
    echo "Waiting for PostgreSQL to be ready"
    sleep 10
done

psql -U sensorthings -d sensorthings <<EOF
DO \$\$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_schema = 'public' AND table_name = 'USERS'
    ) THEN
        CREATE TABLE "USERS" (
            "USER_NAME" TEXT PRIMARY KEY,
            "USER_PASS" TEXT NOT NULL
        );
        CREATE TABLE "USER_ROLES" (
            "USER_NAME" TEXT REFERENCES "USERS"("USER_NAME"),
            "ROLE_NAME" TEXT NOT NULL
        );
        RAISE NOTICE 'USERS table created!';
    ELSE
        RAISE NOTICE 'USERS table already exists.';
    END IF;
END
\$\$;

-- Truncate tables if they exists.
TRUNCATE TABLE "USER_ROLES" CASCADE;
TRUNCATE TABLE "USERS" CASCADE;

-- Update password for existing users (example: admin)
INSERT INTO "USERS" ("USER_NAME", "USER_PASS")
VALUES ('admin', '${POSTGRES_PASSWORD}');

INSERT INTO "USER_ROLES" ("USER_NAME", "ROLE_NAME")
VALUES ('admin', 'admin');

EOF

echo "Database initialization complete."

wait $!