Output start.gif

Set Shell zsh
Set WindowBar Colorful
Set TypingSpeed 0.1s
Set FontSize 20
Set Width 1200
Set Height 300
Set PlaybackSpeed 1

Hide
Type "export PS1='$ '" 
Enter
# 3. Handle your environment setup
Type "source ../../.venv/bin/activate"
Enter
Type "clear"
Enter
Show

# application setup
Type@50ms "#the app starts in public mode by default, but can be set to --private"
Sleep 1
Backspace@10ms 70
Type "stu start "
Enter
Sleep 20

